import React from 'react';
import PropTypes from 'prop-types';
import { Formik } from 'formik';

import { LogoContainer, CardContainer } from './Login.style';
import { Logo, Card, Heading, Alert, FullScreenFlex } from '../shared/ui';
import LoginForm, { LoginSchema } from './Login.form';
import { generateInitialValuesFromSchema } from '../../utils/helpers';

/**
 * Login component displaying our view with login form generated by Formik
 * @param {object} Login component params from our Auth state
 */
const Login = ({ handleLogin, loading, error }) => (
  <FullScreenFlex>
    <LogoContainer>
      <Logo />
    </LogoContainer>
    <Heading textAlign="center">Sign in to Pay Slip Generator</Heading>
    <CardContainer>
      <Card loading={loading}>
        {error && (
          <Alert
            className="login-alert"
            type="danger"
            title="Login failed"
            size="small"
          >
            {error}
          </Alert>
        )}
        <Formik
          onSubmit={handleLogin}
          validationSchema={LoginSchema}
          initialValues={generateInitialValuesFromSchema(
            Object.keys(LoginSchema.fields)
          )}
          render={props => <LoginForm {...props} loginError={error} />}
        />
      </Card>
    </CardContainer>
  </FullScreenFlex>
);

Login.propTypes = {
  /** Function to handle login */
  handleLogin: PropTypes.func.isRequired,
  loading: PropTypes.bool,
  error: PropTypes.string,
};

Login.defaultProps = {
  loading: false,
  error: null,
};

export default Login;
